### PR TITLE
fix #9

### LINKED ISSUE #9: Show type name only when the the struct type is too complex?
https://github.com/Roger-luo/GarishPrint.jl/blob/e45f1178b089895367241358cf01fb4958221131/src/struct.jl#L37

image

So now we simply show `(...)` when `t` is too long. How about trying to display `typeof(t)` only when it exceeds the max length?

### PR DESCRIPTION
**Pull request by findmyway**

### CODE REVIEW

**Comment by Roger-luo** [comment]
I'm wondering if we should print the type parameters in a more structured format instead of printing them in one line?

**Comment by Roger-luo** [comment]
also this PR needs a test case to show the long type printing

**Comment by findmyway** [comment]
> I'm wondering if we should print the type parameters in a more structured format instead of printing them in one line?

I think in most cases it's fine to show parameters in a compact way. The problem I tried to fix here is that sometimes the parameters are too complex and then all the inner data are replaced with `…`

Or maybe a better approach is to TRY to display parameters in one line. If they can’t be fit in one line, then split parameters into multi lines recursively until all of them can be fit in. 

What do you think?

Example:

Current:
```
MyStruct{AAAAAAAAA{BBBB{CCC}},DDDDDD}(…)
```


This PR:

```
MyStruct
```
New proposal:

```
MyStruct{
     AAAAAAAAA{BBBB{CCC}},
     DDDDDD
}
```

**Comment by findmyway** [comment]
That sounds like a very useful feature. We can add it later.

I've updated this PR to fix the original issue, results are shown below:

Wide screen size:

image

Mid screen size:

image

Small screen size:

image

**Comment by Roger-luo** [comment]
nice! Thanks

**Comment by findmyway** [comment]
@Roger-luo  Could you also tag a new release?

**Comment by Roger-luo** [comment]
Yes will do tomorrow can't tag through phone

**Comment by findmyway** [comment]
Thanks! ❤️

**Pull request merged**
